//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Rosgraph
{
    public class Clock : Message
    {
        public const string RosMessageName = "rosgraph_msgs/Clock";

        //  roslib/Clock is used for publishing simulated time in ROS. 
        //  This message simply communicates the current time.
        //  For more information, see http://www.ros.org/wiki/Clock
        public Time clock;

        public Clock()
        {
            this.clock = new Time();
        }

        public Clock(Time clock)
        {
            this.clock = clock;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(clock.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.clock.Deserialize(data, offset);

            return offset;
        }

    }
}
